name: Production Build
on:
  push:
    branches:
      - main

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
    env:
      EXPO_GITHUB_CLIENT_ID: ${{ secrets.EXPO_GITHUB_CLIENT_ID }}
      EXPO_GITHUB_SECRET: ${{ secrets.EXPO_GITHUB_SECRET }}
      EXPO_GITHUB_CLIENT_ID_WEB: ${{ secrets.EXPO_GITHUB_CLIENT_ID_WEB }}
      EXPO_GITHUB_CLIENT_SECRET_WEB: ${{ secrets.EXPO_GITHUB_CLIENT_SECRET_WEB }}
      EXPO_GITHUB_WEB_TOKEN_EXCHANGE_URL: ${{ secrets.EXPO_GITHUB_WEB_TOKEN_EXCHANGE_URL }}
      ENVIRONMENT: production

  post_build:
    type: custom
    needs: [build_android]
    steps:
      - uses: eas/checkout
      - name: Report build
        run: |
          echo "Android production build completed."
          echo "Build ID: ${{ needs.build_android.outputs.build_id }}"
    env:
      ENVIRONMENT: production
