name: Production Build
on:
  push:
    tags:
      - "v*"

jobs:
  build_android:
    type: build
    params:
      platform: android
      profile: production
    env:
      ENVIRONMENT: production

  post_build:
    type: custom
    needs: [build_android]
    steps:
      - uses: eas/checkout
      - name: Report build
        run: |
          echo "Android production build completed."
          echo "Build ID: ${{ needs.build_android.outputs.build_id }}"
    env:
      ENVIRONMENT: production
